default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { nil } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  username: <%= ENV.fetch("DATABASE_USER") { "togodb" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "" } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME_DEVEROPMENT") { "togodb_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME_TEST") { "togodb_test" } %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME_PRODUCTION") { "togodb_production" } %>
