default: &default
  resque:
    data_download_queue:
      name: togodb_v4_dl
      num_workers: 1
    data_import_queue:
      name: togodb_v4_di
      num_workers: 1
    db_copy_queue:
      name: togodb_v4_cp
      num_workers: 1
    data_release_queue:
      name: togodb_v4_re
      num_workers: 1
    new_rdf_repository_queue:
      name: togodb_v4_nr
      num_workers: 1

  run_data_release_after_import: true

  open_search:
    enable: true
    admin_email: togodb-admin@dbcls.jp

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
