module ConfigsHelper

  def rdf_property_term_options(prefix)
    case prefix
    when 'rdf'
      [
          ['first'],
          ['object'],
          ['predicate'],
          ['rest'],
          ['subject'],
          ['type'],
          ['value']
      ]
    when 'rdfs'
      [
          ['comment'],
          ['domain'],
          ['isDefinedBy'],
          ['label'],
          ['member'],
          ['range'],
          ['seeAlso'],
          ['subClassOf'],
          ['subPropertyOf']
      ]
    when 'dc'
      [
          ['contributor'],
          ['coverage'],
          ['creator'],
          ['date'],
          ['description'],
          ['format'],
          ['identifier'],
          ['language'],
          ['publisher'],
          ['relation'],
          ['rights'],
          ['source'],
          ['subject'],
          ['title'],
          ['type']
      ]
    when 'dcterms'
      [
          ['abstract'],
          ['accessRights'],
          ['accrualMethod'],
          ['accrualPeriodicity'],
          ['accrualPolicy'],
          ['alternative'],
          ['audience'],
          ['available'],
          ['bibliographicCitation'],
          ['conformsTo'],
          ['contributor'],
          ['coverage'],
          ['created'],
          ['creator'],
          ['date'],
          ['dateAccepted'],
          ['dateCopyrighted'],
          ['dateSubmitted'],
          ['description'],
          ['educationLevel'],
          ['extent'],
          ['format'],
          ['hasFormat'],
          ['hasPart'],
          ['hasVersion'],
          ['identifier'],
          ['instructionalMethod'],
          ['isFormatOf'],
          ['isPartOf'],
          ['isReferencedBy'],
          ['isReplacedBy'],
          ['isRequiredBy'],
          ['issued'],
          ['isVersionOf'],
          ['language'],
          ['license'],
          ['mediator'],
          ['medium'],
          ['modified'],
          ['provenance'],
          ['publisher'],
          ['references'],
          ['relation'],
          ['replaces'],
          ['requires'],
          ['rights'],
          ['rightsHolder'],
          ['source'],
          ['spatial'],
          ['subject'],
          ['tableOfContents'],
          ['temporal'],
          ['title'],
          ['type'],
          ['valid']
      ]
    when 'foaf'
      [
          ['account'],
          ['accountName'],
          ['accountServiceHomepage'],
          ['age'],
          ['aimChatID'],
          ['based_near'],
          ['birthday'],
          ['currentProject'],
          ['depiction'],
          ['depicts'],
          ['dnaChecksum'],
          ['familyName'],
          ['family_name'],
          ['firstName'],
          ['focus'],
          ['fundedBy'],
          ['geekcode'],
          ['gender'],
          ['givenName'],
          ['givenname'],
          ['holdsAccount'],
          ['homepage'],
          ['icqChatID'],
          ['img'],
          ['interest'],
          ['isPrimaryTopicOf'],
          ['jabberID'],
          ['knows'],
          ['lastName'],
          ['logo'],
          ['made'],
          ['maker'],
          ['mbox'],
          ['mbox_sha1sum'],
          ['member'],
          ['membershipClass'],
          ['msnChatID'],
          ['myersBriggs'],
          ['name'],
          ['nick'],
          ['openid'],
          ['page'],
          ['pastProject'],
          ['phone'],
          ['plan'],
          ['primaryTopic'],
          ['publications'],
          ['schoolHomepage'],
          ['sha1'],
          ['skypeID'],
          ['status'],
          ['surname'],
          ['theme'],
          ['thumbnail'],
          ['tipjar'],
          ['title'],
          ['topic'],
          ['topic_interest'],
          ['weblog'],
          ['workInfoHomepage'],
          ['workplaceHomepage'],
          ['yahooChatID']
      ]
    when 'skos'
      [
          ['altLabel'],
          ['broadMatch'],
          ['broader'],
          ['broaderTransitive'],
          ['changeNote'],
          ['closeMatch'],
          ['definition'],
          ['editorialNote'],
          ['exactMatch'],
          ['example'],
          ['hasTopConcept'],
          ['hiddenLabel'],
          ['historyNote'],
          ['inScheme'],
          ['mappingRelation'],
          ['member'],
          ['memberList'],
          ['narrowMatch'],
          ['narrower'],
          ['narrowerTransitive'],
          ['notation'],
          ['note'],
          ['prefLabel'],
          ['related'],
          ['relatedMatch'],
          ['scopeNote'],
          ['semanticRelation'],
          ['topConceptOf']
      ]
    else
      [
          ['----------', '']
      ]
    end
  end

  def rdf_class_term_options(prefix)
    case prefix
    when 'rdf'
      [
          ['Alt'],
          ['Bag'],
          ['List'],
          ['Property'],
          ['Seq'],
          ['Statement']
      ]
    when 'rdfs'
      [
          ['Class'],
          ['Container'],
          ['ContainerMembershipProperty'],
          ['Datatype'],
          ['Literal'],
          ['Resource']
      ]
    when 'dcterms'
      [
          ['Agent'],
          ['AgentClass'],
          ['BibliographicResource'],
          ['FileFormat'],
          ['Frequency'],
          ['Jurisdiction'],
          ['LicenseDocument'],
          ['LinguisticSystem'],
          ['Location'],
          ['LocationPeriodOrJurisdiction'],
          ['MediaType'],
          ['MediaTypeOrExtent'],
          ['MethodOfAccrual'],
          ['MethodOfInstruction'],
          ['PeriodOfTime'],
          ['PhysicalMedium'],
          ['PhysicalResource'],
          ['Policy'],
          ['ProvenanceStatement'],
          ['RightsStatement'],
          ['SizeOrDuration'],
          ['Standard']
      ]
    when 'foaf'
      [
          ['Agent'],
          ['Document'],
          ['Group'],
          ['Image'],
          ['LabelProperty'],
          ['OnlineAccount'],
          ['OnlineChatAccount'],
          ['OnlineEcommerceAccount'],
          ['OnlineGamingAccount'],
          ['Organization'],
          ['Person'],
          ['PersonalProfileDocument'],
          ['Project']
      ]
    when 'skos'
      [
          ['Collection'],
          ['Concept'],
          ['ConceptScheme'],
          ['OrderedCollection']
      ]
    else
      [
          ['----------', '']
      ]
    end
  end

end
